# Generated by Django 3.0.14 on 2021-10-16 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(default='fuckyoudjango', max_length=200),
        ),
    ]
